# Migration 0065: Cria schema SAP com tabelas bukrs e relatorio_custo.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_certificadodigital_senha_certificado'),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS "sap";',
            reverse_sql='DROP SCHEMA IF EXISTS "sap" CASCADE;',
        ),
        migrations.CreateModel(
            name='Bukrs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bukrs', models.CharField(db_index=True, max_length=4, unique=True, verbose_name='Código da empresa')),
                ('butext', models.CharField(blank=True, max_length=35, null=True, verbose_name='Denominação')),
            ],
            options={
                'db_table': '"sap"."bukrs"',
                'managed': True,
                'ordering': ['bukrs'],
                'verbose_name': 'Empresa SAP',
                'verbose_name_plural': 'Empresas SAP',
            },
        ),
        migrations.CreateModel(
            name='RelatorioCusto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('docnum', models.CharField(max_length=20, verbose_name='Nº Documento')),
                ('mjahr', models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano do Documento')),
                ('mblnr', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nº Documento de Material')),
                ('matnr', models.CharField(blank=True, max_length=18, null=True, verbose_name='Nº do Material')),
                ('nfenum', models.CharField(blank=True, max_length=9, null=True, verbose_name='Número de Documento (9 posições)')),
                ('series', models.CharField(blank=True, max_length=3, null=True, verbose_name='Série')),
                ('docsta', models.CharField(max_length=1, verbose_name='Status do Documento')),
                ('kunnr', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nº Cliente')),
                ('name1', models.CharField(blank=True, max_length=35, null=True, verbose_name='Cliente')),
                ('ort01', models.CharField(blank=True, max_length=35, null=True, verbose_name='Cidade')),
                ('chave_acesso', models.CharField(blank=True, max_length=44, null=True, verbose_name='Chave de Acesso')),
                ('itmnum', models.CharField(blank=True, max_length=6, null=True, verbose_name='Nº Item do Documento')),
                ('pstdat', models.DateField(blank=True, null=True, verbose_name='Data de Postagem')),
                ('werks', models.CharField(blank=True, max_length=4, null=True, verbose_name='Local de Negócios')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome')),
                ('stcd1', models.CharField(blank=True, max_length=16, null=True, verbose_name='CNPJ')),
                ('uf_origem', models.CharField(blank=True, max_length=3, null=True, verbose_name='UF de Origem')),
                ('uf_destino', models.CharField(blank=True, max_length=3, null=True, verbose_name='UF de Destino')),
                ('cancel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status de Cancelamento')),
                ('maktx', models.CharField(blank=True, max_length=40, null=True, verbose_name='Texto Breve do Material')),
                ('mtart', models.CharField(blank=True, max_length=4, null=True, verbose_name='Tipo de Material')),
                ('matkl', models.CharField(blank=True, max_length=9, null=True, verbose_name='Grupo de Mercadorias')),
                ('wgbez', models.CharField(blank=True, max_length=20, null=True, verbose_name='Denominação do Grupo de Mercadorias')),
                ('cfop', models.CharField(blank=True, max_length=10, null=True, verbose_name='CFOP')),
                ('qtd_prod', models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True, verbose_name='Quantidade de Produto')),
                ('unid_medida', models.CharField(blank=True, max_length=3, null=True, verbose_name='Unidade de Medida de Venda')),
                ('meins', models.CharField(blank=True, max_length=3, null=True, verbose_name='Unidade de Medida Básica')),
                ('umrez', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='Contador Conversão UM')),
                ('menge_umb', models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True, verbose_name='Qtd Convertida p/ UM Básica')),
                ('prc_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Preço Unitário')),
                ('prc_unit_cst_liq', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Preço Unitário Custo Líquido')),
                ('prc_unit_cst_adm', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Preço Unitário Custo ADM')),
                ('bc_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Base de Cálculo ICMS')),
                ('pct_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Alíquota ICMS')),
                ('vlr_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Valor ICMS')),
                ('bc_icms_st', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Base ICMS ST')),
                ('alq_st', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Alíquota ICMS ST')),
                ('vlr_st', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Valor ICMS ST')),
                ('bc_ipi', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Base IPI')),
                ('pct_ipi', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Alíquota IPI')),
                ('vlr_ipi', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Valor IPI')),
                ('bc_pis', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Base PIS')),
                ('pct_pis', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Alíquota PIS')),
                ('vlr_pis', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Valor PIS')),
                ('bc_cof', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Base COFINS')),
                ('pct_cof', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Alíquota COFINS')),
                ('vlr_cof', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Valor COFINS')),
                ('tp_doc', models.CharField(blank=True, max_length=2, null=True, verbose_name='Tipo de Documento')),
                ('total_impostos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total de Impostos')),
                ('vlr_desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Valor de Desconto')),
                ('vlr_frete', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Valor do Frete')),
                ('vlr_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Valor Líquido')),
                ('vlr_tot_doc', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Valor Total do Documento')),
                ('cmv', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='CMV')),
                ('lucro_0', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Lucro 0')),
                ('margem_0', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Margem 0')),
                ('margem_contrib', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Margem Contribuição')),
                ('cmv_gerencial', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='CMV Gerencial')),
                ('lucro_0_gerencial', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Lucro 0 Gerencial')),
                ('margem_real', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Margem Real')),
                ('lucro_real', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Lucro Real')),
                ('margem_contrib_ger', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Margem Contribuição Gerencial')),
                ('cmv_media', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='CMV Média')),
                ('per_taxa_adm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Percentual Taxa ADM')),
                ('vlr_taxa_adm', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Valor Taxa ADM')),
                ('per_taxa_frt', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Percentual Taxa Frete')),
                ('vlr_taxa_frt', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Valor Taxa Frete')),
                ('cmv_ue', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='CMV Última Entrada')),
                ('bukrs', models.ForeignKey(blank=True, db_column='bukrs_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relatorios_custo', to='app.bukrs', verbose_name='Empresa')),
            ],
            options={
                'db_table': '"sap"."relatorio_custo"',
                'managed': True,
                'ordering': ['-pstdat', 'docnum'],
                'verbose_name': 'Relatório de Custo',
                'verbose_name_plural': 'Relatórios de Custo',
                'unique_together': {('bukrs', 'docnum', 'mjahr', 'mblnr')},
            },
        ),
        migrations.AddIndex(
            model_name='relatoriocusto',
            index=models.Index(fields=['bukrs', 'docnum', 'mjahr', 'mblnr'], name='sap_relcusto_bukrs_idx'),
        ),
        migrations.AddIndex(
            model_name='relatoriocusto',
            index=models.Index(fields=['pstdat'], name='sap_relcusto_pstdat_idx'),
        ),
        migrations.AddIndex(
            model_name='relatoriocusto',
            index=models.Index(fields=['chave_acesso'], name='sap_relcusto_chave_idx'),
        ),
    ]
