# Generated by Django 5.2.11 on 2026-06-30 18:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_remove_subsolucao_pro_relatorio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empresa',
            new_name='Empresas',
        ),
        migrations.CreateModel(
            name='GrpEmpresas',
            fields=[
                ('grp_empresa', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'verbose_name': 'Grupo de empresas',
                'verbose_name_plural': 'Grupos de empresas',
                'db_table': 'grp_empresas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SpedContribuicaoArquivo',
            fields=[
                ('id_arquivo', models.AutoField(primary_key=True, serialize=False)),
                ('competencia', models.DateField(blank=True, null=True)),
                ('nome_arquivo', models.CharField(blank=True, max_length=255, null=True)),
                ('hash_conteudo', models.CharField(blank=True, max_length=64, null=True)),
                ('data_carga', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"sped_contribuicao"."sped_arquivo"',
                'ordering': ['-data_carga'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SpedContribuicaoReg_C190',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('linha', models.IntegerField(blank=True, null=True)),
                ('cod_item', models.CharField(blank=True, db_index=True, max_length=60, null=True)),
                ('cfop', models.CharField(blank=True, max_length=4, null=True)),
                ('cst_pis', models.CharField(blank=True, max_length=2, null=True)),
                ('vl_bc_pis', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_pis', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cst_cofins', models.CharField(blank=True, max_length=2, null=True)),
                ('vl_bc_cofins', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_cofins', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_opr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cst_icms', models.CharField(blank=True, max_length=3, null=True)),
                ('aliq_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_bc_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_bc_icms_st', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_icms_st', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_red_bc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_ipi', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cod_obs', models.CharField(blank=True, max_length=6, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"sped_contribuicao"."sped_reg_c190"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SpedFiscalArquivo',
            fields=[
                ('id_arquivo', models.AutoField(primary_key=True, serialize=False)),
                ('competencia', models.DateField(blank=True, null=True)),
                ('nome_arquivo', models.CharField(blank=True, max_length=255, null=True)),
                ('hash_conteudo', models.CharField(blank=True, max_length=64, null=True)),
                ('data_carga', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"sped_fiscal"."sped_arquivo"',
                'ordering': ['-data_carga'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SpedFiscalReg_0000',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('linha', models.IntegerField(blank=True, null=True)),
                ('cod_ver', models.CharField(blank=True, max_length=3, null=True)),
                ('cod_fin', models.CharField(blank=True, max_length=1, null=True)),
                ('dt_ini', models.DateField(blank=True, null=True)),
                ('dt_fin', models.DateField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('ie', models.CharField(blank=True, max_length=14, null=True)),
                ('cod_mun', models.CharField(blank=True, max_length=7, null=True)),
                ('im', models.CharField(blank=True, max_length=15, null=True)),
                ('suframa', models.CharField(blank=True, max_length=9, null=True)),
                ('ind_perfil', models.CharField(blank=True, max_length=1, null=True)),
                ('ind_ativ', models.CharField(blank=True, max_length=1, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"sped_fiscal"."sped_reg_0000"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SpedFiscalReg_0001',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('linha', models.IntegerField(blank=True, null=True)),
                ('ind_mov', models.CharField(blank=True, max_length=1, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"sped_fiscal"."sped_reg_0001"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SpedFiscalReg_0005',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('linha', models.IntegerField(blank=True, null=True)),
                ('fantasia', models.CharField(blank=True, max_length=60, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('end', models.CharField(blank=True, max_length=60, null=True)),
                ('num', models.CharField(blank=True, max_length=10, null=True)),
                ('compl', models.CharField(blank=True, max_length=60, null=True)),
                ('bairro', models.CharField(blank=True, max_length=60, null=True)),
                ('fone', models.CharField(blank=True, max_length=11, null=True)),
                ('fax', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"sped_fiscal"."sped_reg_0005"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SpedFiscalReg_0150',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('linha', models.IntegerField(blank=True, null=True)),
                ('cod_part', models.CharField(blank=True, db_index=True, max_length=60, null=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_pais', models.CharField(blank=True, max_length=3, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('ie', models.CharField(blank=True, max_length=14, null=True)),
                ('cod_mun', models.CharField(blank=True, max_length=7, null=True)),
                ('end', models.CharField(blank=True, max_length=60, null=True)),
                ('num', models.CharField(blank=True, max_length=10, null=True)),
                ('compl', models.CharField(blank=True, max_length=60, null=True)),
                ('bairro', models.CharField(blank=True, max_length=60, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"sped_fiscal"."sped_reg_0150"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SpedFiscalReg_0190',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('linha', models.IntegerField(blank=True, null=True)),
                ('unid', models.CharField(blank=True, max_length=6, null=True)),
                ('descr', models.CharField(blank=True, max_length=255, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"sped_fiscal"."sped_reg_0190"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SpedFiscalReg_0200',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('linha', models.IntegerField(blank=True, null=True)),
                ('cod_item', models.CharField(blank=True, db_index=True, max_length=60, null=True)),
                ('descr_item', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_barra', models.CharField(blank=True, max_length=14, null=True)),
                ('cod_ant_item', models.CharField(blank=True, max_length=60, null=True)),
                ('unid_inv', models.CharField(blank=True, max_length=6, null=True)),
                ('tipo_item', models.CharField(blank=True, max_length=2, null=True)),
                ('cod_ncm', models.CharField(blank=True, max_length=8, null=True)),
                ('ex_ipi', models.CharField(blank=True, max_length=3, null=True)),
                ('cod_gen', models.CharField(blank=True, max_length=2, null=True)),
                ('cod_lst', models.CharField(blank=True, max_length=5, null=True)),
                ('aliq_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"sped_fiscal"."sped_reg_0200"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SpedFiscalReg_C001',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('linha', models.IntegerField(blank=True, null=True)),
                ('ind_mov', models.CharField(blank=True, max_length=1, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"sped_fiscal"."sped_reg_c001"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SpedFiscalReg_C100',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('linha', models.IntegerField(blank=True, null=True)),
                ('ind_oper', models.CharField(blank=True, max_length=1, null=True)),
                ('ind_emit', models.CharField(blank=True, max_length=1, null=True)),
                ('cod_part', models.CharField(blank=True, max_length=60, null=True)),
                ('cod_mod', models.CharField(blank=True, max_length=2, null=True)),
                ('cod_sit', models.CharField(blank=True, max_length=2, null=True)),
                ('ser', models.CharField(blank=True, max_length=3, null=True)),
                ('num_doc', models.CharField(blank=True, max_length=9, null=True)),
                ('chv_nfe', models.CharField(blank=True, max_length=44, null=True)),
                ('dt_doc', models.DateField(blank=True, null=True)),
                ('dt_e_s', models.DateField(blank=True, null=True)),
                ('vl_doc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ind_frt', models.CharField(blank=True, max_length=1, null=True)),
                ('vl_frt', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_seg', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_out_da', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_bc_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_bc_icms_st', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_icms_st', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_ipi', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_pis', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_cofins', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_pis_st', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_cofins_st', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"sped_fiscal"."sped_reg_c100"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SpedFiscalReg_C170',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('linha', models.IntegerField(blank=True, null=True)),
                ('num_item', models.CharField(blank=True, max_length=3, null=True)),
                ('cod_item', models.CharField(blank=True, max_length=60, null=True)),
                ('descr_compl', models.CharField(blank=True, max_length=255, null=True)),
                ('qtd', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('unid', models.CharField(blank=True, max_length=6, null=True)),
                ('vl_item', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_desc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ind_mov', models.CharField(blank=True, max_length=1, null=True)),
                ('cst_icms', models.CharField(blank=True, max_length=3, null=True)),
                ('cfop', models.CharField(blank=True, max_length=4, null=True)),
                ('cod_nat', models.CharField(blank=True, max_length=10, null=True)),
                ('vl_bc_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('aliq_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_bc_icms_st', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('aliq_st', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_icms_st', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cst_pis', models.CharField(blank=True, max_length=2, null=True)),
                ('vl_bc_pis', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('aliq_pis', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('vl_pis', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cst_cofins', models.CharField(blank=True, max_length=2, null=True)),
                ('vl_bc_cofins', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('aliq_cofins', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('vl_cofins', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"sped_fiscal"."sped_reg_c170"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SpedFiscalReg_D100',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('linha', models.IntegerField(blank=True, null=True)),
                ('ind_oper', models.CharField(blank=True, max_length=1, null=True)),
                ('ind_emit', models.CharField(blank=True, max_length=1, null=True)),
                ('cod_part', models.CharField(blank=True, max_length=60, null=True)),
                ('cod_mod', models.CharField(blank=True, max_length=2, null=True)),
                ('cod_sit', models.CharField(blank=True, max_length=2, null=True)),
                ('ser', models.CharField(blank=True, max_length=3, null=True)),
                ('sub_ser', models.CharField(blank=True, max_length=3, null=True)),
                ('num_doc', models.CharField(blank=True, max_length=9, null=True)),
                ('chv_cte', models.CharField(blank=True, max_length=44, null=True)),
                ('dt_doc', models.DateField(blank=True, null=True)),
                ('dt_a_p', models.DateField(blank=True, null=True)),
                ('tp_ct_e', models.CharField(blank=True, max_length=1, null=True)),
                ('chv_cte_ref', models.CharField(blank=True, max_length=44, null=True)),
                ('vl_doc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_desc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ind_frt', models.CharField(blank=True, max_length=1, null=True)),
                ('vl_frt', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_seg', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_out_da', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_bc_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_nf', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cod_inf', models.CharField(blank=True, max_length=6, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"sped_fiscal"."sped_reg_d100"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SpedFiscalRegistro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registro', models.CharField(db_index=True, max_length=20)),
                ('linha', models.IntegerField(blank=True, null=True)),
                ('campos', models.JSONField(blank=True, default=dict)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"sped_fiscal"."sped_registro"',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='sped_arquivo',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='sped_arquivo',
            name='cliente',
        ),
        migrations.AlterModelOptions(
            name='acessosolucaocliente',
            options={'managed': True, 'verbose_name': 'Acesso solução (cliente)', 'verbose_name_plural': 'Acessos solução (cliente)'},
        ),
        migrations.AlterModelOptions(
            name='acessosubsolucaogrupo',
            options={'managed': True, 'verbose_name': 'Acesso subsolução (grupo)', 'verbose_name_plural': 'Acessos subsolução (grupo)'},
        ),
        migrations.AlterModelOptions(
            name='clientegdf',
            options={'managed': True, 'verbose_name': 'Cliente GDF', 'verbose_name_plural': 'Clientes GDF'},
        ),
        migrations.AlterModelOptions(
            name='conexaosap',
            options={'managed': True, 'verbose_name': 'Conexão SAP', 'verbose_name_plural': 'Conexões SAP'},
        ),
        migrations.AlterModelOptions(
            name='jobcargasped',
            options={'managed': True, 'verbose_name': 'Job carga SPED', 'verbose_name_plural': 'Jobs carga SPED'},
        ),
        migrations.AlterModelOptions(
            name='jobcargaxml',
            options={'managed': True, 'verbose_name': 'Job carga XML', 'verbose_name_plural': 'Jobs carga XML'},
        ),
        migrations.AlterModelOptions(
            name='permissaogrupocliente',
            options={'managed': True, 'verbose_name': 'Permissão grupo-cliente', 'verbose_name_plural': 'Permissões grupo-cliente'},
        ),
        migrations.AlterModelOptions(
            name='solucao',
            options={'managed': True, 'verbose_name': 'Solução', 'verbose_name_plural': 'Soluções'},
        ),
        migrations.AlterModelOptions(
            name='subsolucao',
            options={'managed': True, 'verbose_name': 'Subsolução', 'verbose_name_plural': 'Subsoluções'},
        ),
        migrations.AlterModelOptions(
            name='usuarioempresa',
            options={'managed': True, 'verbose_name': 'Usuário-Empresa', 'verbose_name_plural': 'Usuários-Empresas'},
        ),
        migrations.RemoveConstraint(
            model_name='filial',
            name='filial_empresa_cod_filial_uniq',
        ),
        migrations.RemoveIndex(
            model_name='jobcargasped',
            name='cargasped_j_cliente_88ec61_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobcargaxml',
            name='cargaxml_jo_cliente_763bcd_idx',
        ),
        migrations.RemoveIndex(
            model_name='nfe',
            name='nfe_cod_cli_263006_idx',
        ),
        migrations.RemoveIndex(
            model_name='reprocessamentolote',
            name='reprocessam_grp_emp_grp_emp_idx',
        ),
        migrations.RenameIndex(
            model_name='clientegdf',
            new_name='cliente_gdf_cnpj_3df010_idx',
            old_name='clientes_cnpj_7b9982_idx',
        ),
        migrations.RenameIndex(
            model_name='condicaoparam',
            new_name='condicao_pa_cod_cli_4ca465_idx',
            old_name='condicao_pa_gdfclie_condica_idx',
        ),
        migrations.RenameIndex(
            model_name='filial',
            new_name='filial_empresa_b3e3b8_idx',
            old_name='filial_empresa_cod_fil_idx',
        ),
        migrations.RenameIndex(
            model_name='relatoriocusto',
            new_name='relatorio_c_cod_emp_7bf7a9_idx',
            old_name='sap_relcusto_empresa_idx',
        ),
        migrations.RenameIndex(
            model_name='relatoriocusto',
            new_name='relatorio_c_pstdat_99fce3_idx',
            old_name='sap_relcusto_pstdat_idx',
        ),
        migrations.RenameIndex(
            model_name='relatoriocusto',
            new_name='relatorio_c_chave_a_853ddb_idx',
            old_name='sap_relcusto_chave_idx',
        ),
        migrations.RenameIndex(
            model_name='reprocessamentolote',
            new_name='reprocessam_cod_emp_b36c98_idx',
            old_name='reprocessam_empresa_comp_idx',
        ),
        migrations.AlterField(
            model_name='condicaoparam',
            name='gdfcliente',
            field=models.ForeignKey(blank=True, db_column='cod_cliente', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condicoes_param_reprocessamento', to='app.clientegdf'),
        ),
        migrations.AlterField(
            model_name='nfe',
            name='sap_nome_tabela',
            field=models.CharField(blank=True, help_text='Nome da tabela SAP onde o documento foi localizado (NAME_TABLE na RFC, até 30 caracteres).', max_length=30, null=True),
        ),
        migrations.AddIndex(
            model_name='divergencia',
            index=models.Index(fields=['lote', 'tipo', 'status'], name='divergencia_lote_id_8e649f_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcargasped',
            index=models.Index(fields=['gdfcliente', 'status'], name='job_carga_s_gdfclie_813380_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcargasped',
            index=models.Index(fields=['gdfcliente', 'started_at'], name='job_carga_s_gdfclie_b69320_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcargaxml',
            index=models.Index(fields=['gdfcliente', 'status'], name='job_carga_x_gdfclie_958ddf_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcargaxml',
            index=models.Index(fields=['gdfcliente', 'started_at'], name='job_carga_x_gdfclie_3f1013_idx'),
        ),
        migrations.RenameModel(
            old_name='CertificadoDigital',
            new_name='Cert',
        ),
        migrations.AlterModelTable(
            name='cert',
            table='cert',
        ),
        migrations.AlterModelOptions(
            name='cert',
            options={'managed': True, 'verbose_name': 'Certificado digital', 'verbose_name_plural': 'Certificados digitais'},
        ),
        migrations.AlterField(
            model_name='cte',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.empresas'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiais', to='app.empresas'),
        ),
        migrations.AlterField(
            model_name='nfe',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nfe_docs', to='app.empresas'),
        ),
        migrations.AlterField(
            model_name='nfse',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.empresas'),
        ),
        migrations.AlterField(
            model_name='relatoriocusto',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='cod_empresa_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relatorios_custo_sap', to='app.empresas', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='reprocessamentolote',
            name='empresa',
            field=models.ForeignKey(db_column='cod_empresa_id', on_delete=django.db.models.deletion.CASCADE, related_name='reprocessamento_lotes', to='app.empresas'),
        ),
        migrations.AlterField(
            model_name='usuarioempresa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresas'),
        ),
        migrations.AlterUniqueTogether(
            name='filial',
            unique_together={('empresa', 'cod_filial')},
        ),
        migrations.AddIndex(
            model_name='nfe',
            index=models.Index(fields=['gdfcliente'], name='nfe_cod_cli_263006_idx'),
        ),
        migrations.AddField(
            model_name='grpempresas',
            name='cliente',
            field=models.ForeignKey(blank=True, db_column='gdfcliente_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.clientegdf'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='grp_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.grpempresas'),
        ),
        migrations.RenameModel(
            old_name='Sped_Reg_0000',
            new_name='SpedContribuicaoReg_0000',
        ),
        migrations.RenameIndex(
            model_name='spedcontribuicaoreg_0000',
            new_name='sc_reg_0000_arquivo',
            old_name='sped_reg_00_arquivo_8d767f_idx',
        ),
        migrations.AlterModelTable(
            name='spedcontribuicaoreg_0000',
            table='"sped_contribuicao"."sped_reg_0000"',
        ),
        migrations.RenameModel(
            old_name='Sped_Reg_0001',
            new_name='SpedContribuicaoReg_0001',
        ),
        migrations.RenameIndex(
            model_name='spedcontribuicaoreg_0001',
            new_name='sc_reg_0001_arquivo',
            old_name='sped_reg_00_arquivo_efda49_idx',
        ),
        migrations.AlterModelTable(
            name='spedcontribuicaoreg_0001',
            table='"sped_contribuicao"."sped_reg_0001"',
        ),
        migrations.RenameModel(
            old_name='Sped_Reg_0005',
            new_name='SpedContribuicaoReg_0005',
        ),
        migrations.RenameIndex(
            model_name='spedcontribuicaoreg_0005',
            new_name='sc_reg_0005_arquivo',
            old_name='sped_reg_00_arquivo_6a4192_idx',
        ),
        migrations.AlterModelTable(
            name='spedcontribuicaoreg_0005',
            table='"sped_contribuicao"."sped_reg_0005"',
        ),
        migrations.RenameModel(
            old_name='Sped_Reg_0150',
            new_name='SpedContribuicaoReg_0150',
        ),
        migrations.RenameIndex(
            model_name='spedcontribuicaoreg_0150',
            new_name='sc_reg_0150_arquivo',
            old_name='sped_reg_01_arquivo_8d3991_idx',
        ),
        migrations.RenameIndex(
            model_name='spedcontribuicaoreg_0150',
            new_name='sc_reg_0150_codpart',
            old_name='sped_reg_01_cod_par_828512_idx',
        ),
        migrations.AlterModelTable(
            name='spedcontribuicaoreg_0150',
            table='"sped_contribuicao"."sped_reg_0150"',
        ),
        migrations.RenameModel(
            old_name='Sped_Reg_0190',
            new_name='SpedContribuicaoReg_0190',
        ),
        migrations.RenameIndex(
            model_name='spedcontribuicaoreg_0190',
            new_name='sc_reg_0190_arquivo',
            old_name='sped_reg_01_arquivo_a4a4d6_idx',
        ),
        migrations.AlterModelTable(
            name='spedcontribuicaoreg_0190',
            table='"sped_contribuicao"."sped_reg_0190"',
        ),
        migrations.RenameModel(
            old_name='Sped_Reg_0200',
            new_name='SpedContribuicaoReg_0200',
        ),
        migrations.RenameIndex(
            model_name='spedcontribuicaoreg_0200',
            new_name='sc_reg_0200_arquivo',
            old_name='sped_reg_02_arquivo_503e97_idx',
        ),
        migrations.RenameIndex(
            model_name='spedcontribuicaoreg_0200',
            new_name='sc_reg_0200_coditem',
            old_name='sped_reg_02_cod_ite_4ba27d_idx',
        ),
        migrations.AlterModelTable(
            name='spedcontribuicaoreg_0200',
            table='"sped_contribuicao"."sped_reg_0200"',
        ),
        migrations.RenameModel(
            old_name='Sped_Reg_C001',
            new_name='SpedContribuicaoReg_C001',
        ),
        migrations.RenameIndex(
            model_name='spedcontribuicaoreg_c001',
            new_name='sc_reg_c001_arquivo',
            old_name='sped_reg_c0_arquivo_220180_idx',
        ),
        migrations.AlterModelTable(
            name='spedcontribuicaoreg_c001',
            table='"sped_contribuicao"."sped_reg_c001"',
        ),
        migrations.RenameModel(
            old_name='Sped_Reg_C170',
            new_name='SpedContribuicaoReg_C170',
        ),
        migrations.RenameIndex(
            model_name='spedcontribuicaoreg_c170',
            new_name='sc_reg_c170_arquivo',
            old_name='sped_reg_c1_arquivo_7c8311_idx',
        ),
        migrations.RenameIndex(
            model_name='spedcontribuicaoreg_c170',
            new_name='sc_reg_c170_c100',
            old_name='sped_reg_c1_c100_id_b1ea62_idx',
        ),
        migrations.AlterModelTable(
            name='spedcontribuicaoreg_c170',
            table='"sped_contribuicao"."sped_reg_c170"',
        ),
        migrations.RenameModel(
            old_name='Sped_Reg_D100',
            new_name='SpedContribuicaoReg_D100',
        ),
        migrations.RemoveIndex(
            model_name='spedcontribuicaoreg_d100',
            name='sped_reg_d1_dt_doc_0fbe6a_idx',
        ),
        migrations.RenameIndex(
            model_name='spedcontribuicaoreg_d100',
            new_name='sc_reg_d100_arquivo',
            old_name='sped_reg_d1_arquivo_5b8556_idx',
        ),
        migrations.RenameIndex(
            model_name='spedcontribuicaoreg_d100',
            new_name='sc_reg_d100_chv',
            old_name='sped_reg_d1_chv_cte_d3e12a_idx',
        ),
        migrations.AlterModelTable(
            name='spedcontribuicaoreg_d100',
            table='"sped_contribuicao"."sped_reg_d100"',
        ),
        migrations.RenameModel(
            old_name='Sped_Registro',
            new_name='SpedContribuicaoRegistro',
        ),
        migrations.RenameIndex(
            model_name='spedcontribuicaoregistro',
            new_name='sc_registro_arquivo',
            old_name='sped_regist_arquivo_1ba485_idx',
        ),
        migrations.RenameIndex(
            model_name='spedcontribuicaoregistro',
            new_name='sc_registro_arq_reg',
            old_name='sped_regist_arquivo_edcd8a_idx',
        ),
        migrations.AlterModelTable(
            name='spedcontribuicaoregistro',
            table='"sped_contribuicao"."sped_registro"',
        ),
        migrations.AddField(
            model_name='spedcontribuicaoarquivo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sped_contribuicao_arquivos', to='app.empresas'),
        ),
        migrations.AddField(
            model_name='spedcontribuicaoarquivo',
            name='gdfcliente',
            field=models.ForeignKey(blank=True, db_column='cod_cliente', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sped_contribuicao_arquivos', to='app.clientegdf'),
        ),
        migrations.AlterField(
            model_name='spedcontribuicaoreg_0000',
            name='arquivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_0000', to='app.spedcontribuicaoarquivo'),
        ),
        migrations.AlterField(
            model_name='spedcontribuicaoreg_0001',
            name='arquivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_0001', to='app.spedcontribuicaoarquivo'),
        ),
        migrations.AlterField(
            model_name='spedcontribuicaoreg_0005',
            name='arquivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_0005', to='app.spedcontribuicaoarquivo'),
        ),
        migrations.AlterField(
            model_name='spedcontribuicaoreg_0150',
            name='arquivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_0150', to='app.spedcontribuicaoarquivo'),
        ),
        migrations.AlterField(
            model_name='spedcontribuicaoreg_0190',
            name='arquivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_0190', to='app.spedcontribuicaoarquivo'),
        ),
        migrations.AlterField(
            model_name='spedcontribuicaoreg_0200',
            name='arquivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_0200', to='app.spedcontribuicaoarquivo'),
        ),
        migrations.AlterField(
            model_name='spedcontribuicaoreg_c001',
            name='arquivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_c001', to='app.spedcontribuicaoarquivo'),
        ),
        migrations.AlterField(
            model_name='spedcontribuicaoreg_c170',
            name='arquivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_c170', to='app.spedcontribuicaoarquivo'),
        ),
        migrations.AlterField(
            model_name='spedcontribuicaoreg_d100',
            name='arquivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_d100', to='app.spedcontribuicaoarquivo'),
        ),
        migrations.AlterField(
            model_name='spedcontribuicaoregistro',
            name='arquivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='app.spedcontribuicaoarquivo'),
        ),
        migrations.RenameModel(
            old_name='Sped_Reg_C100',
            new_name='SpedContribuicaoReg_C100',
        ),
        migrations.RemoveIndex(
            model_name='spedcontribuicaoreg_c100',
            name='sped_reg_c1_dt_doc_7973f1_idx',
        ),
        migrations.AlterField(
            model_name='spedcontribuicaoreg_c100',
            name='arquivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_c100', to='app.spedcontribuicaoarquivo'),
        ),
        migrations.RenameIndex(
            model_name='spedcontribuicaoreg_c100',
            new_name='sc_reg_c100_arquivo',
            old_name='sped_reg_c1_arquivo_c44b31_idx',
        ),
        migrations.RenameIndex(
            model_name='spedcontribuicaoreg_c100',
            new_name='sc_reg_c100_chv',
            old_name='sped_reg_c1_chv_nfe_c1ff76_idx',
        ),
        migrations.AlterModelTable(
            name='spedcontribuicaoreg_c100',
            table='"sped_contribuicao"."sped_reg_c100"',
        ),
        migrations.AddField(
            model_name='spedcontribuicaoreg_c190',
            name='arquivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_c190', to='app.spedcontribuicaoarquivo'),
        ),
        migrations.AddField(
            model_name='spedcontribuicaoreg_c190',
            name='c100',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_c190', to='app.spedcontribuicaoreg_c100'),
        ),
        migrations.AddField(
            model_name='spedfiscalarquivo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sped_fiscal_arquivos', to='app.empresas'),
        ),
        migrations.AddField(
            model_name='spedfiscalarquivo',
            name='gdfcliente',
            field=models.ForeignKey(blank=True, db_column='cod_cliente', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sped_fiscal_arquivos', to='app.clientegdf'),
        ),
        migrations.AddField(
            model_name='spedfiscalreg_0000',
            name='arquivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_0000', to='app.spedfiscalarquivo'),
        ),
        migrations.AddField(
            model_name='spedfiscalreg_0001',
            name='arquivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_0001', to='app.spedfiscalarquivo'),
        ),
        migrations.AddField(
            model_name='spedfiscalreg_0005',
            name='arquivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_0005', to='app.spedfiscalarquivo'),
        ),
        migrations.AddField(
            model_name='spedfiscalreg_0150',
            name='arquivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_0150', to='app.spedfiscalarquivo'),
        ),
        migrations.AddField(
            model_name='spedfiscalreg_0190',
            name='arquivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_0190', to='app.spedfiscalarquivo'),
        ),
        migrations.AddField(
            model_name='spedfiscalreg_0200',
            name='arquivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_0200', to='app.spedfiscalarquivo'),
        ),
        migrations.AddField(
            model_name='spedfiscalreg_c001',
            name='arquivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_c001', to='app.spedfiscalarquivo'),
        ),
        migrations.RenameModel(
            old_name='Sped_Reg_C190',
            new_name='SpedFiscalReg_C190',
        ),
        migrations.AlterField(
            model_name='spedfiscalreg_c190',
            name='arquivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_c190', to='app.spedfiscalarquivo'),
        ),
        migrations.RenameIndex(
            model_name='spedfiscalreg_c190',
            new_name='sf_reg_c190_arquivo',
            old_name='sped_reg_c1_arquivo_38743e_idx',
        ),
        migrations.RenameIndex(
            model_name='spedfiscalreg_c190',
            new_name='sf_reg_c190_c100',
            old_name='sped_reg_c1_c100_id_ac946f_idx',
        ),
        migrations.AlterModelTable(
            name='spedfiscalreg_c190',
            table='"sped_fiscal"."sped_reg_c190"',
        ),
        migrations.AddField(
            model_name='spedfiscalreg_c100',
            name='arquivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_c100', to='app.spedfiscalarquivo'),
        ),
        migrations.AlterField(
            model_name='spedfiscalreg_c190',
            name='c100',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_c190', to='app.spedfiscalreg_c100'),
        ),
        migrations.AddField(
            model_name='spedfiscalreg_c170',
            name='arquivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_c170', to='app.spedfiscalarquivo'),
        ),
        migrations.AddField(
            model_name='spedfiscalreg_c170',
            name='c100',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_c170', to='app.spedfiscalreg_c100'),
        ),
        migrations.AddField(
            model_name='spedfiscalreg_d100',
            name='arquivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_d100', to='app.spedfiscalarquivo'),
        ),
        migrations.AddField(
            model_name='spedfiscalregistro',
            name='arquivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='app.spedfiscalarquivo'),
        ),
        migrations.DeleteModel(
            name='Sped_Arquivo',
        ),
        migrations.AddIndex(
            model_name='empresas',
            index=models.Index(fields=['cnpj', 'razao', 'fantasia'], name='empresa_cnpj_9e4098_idx'),
        ),
        migrations.AddIndex(
            model_name='spedcontribuicaoarquivo',
            index=models.Index(fields=['gdfcliente', 'competencia'], name='sc_arquivo_cli_comp'),
        ),
        migrations.AddIndex(
            model_name='spedcontribuicaoarquivo',
            index=models.Index(fields=['empresa', 'competencia'], name='sc_arquivo_emp_comp'),
        ),
        migrations.AddIndex(
            model_name='spedcontribuicaoarquivo',
            index=models.Index(fields=['data_carga'], name='sc_arquivo_data_carga'),
        ),
        migrations.AddIndex(
            model_name='spedcontribuicaoarquivo',
            index=models.Index(fields=['hash_conteudo'], name='sc_arquivo_hash'),
        ),
        migrations.AddIndex(
            model_name='spedcontribuicaoreg_c190',
            index=models.Index(fields=['arquivo'], name='sc_reg_c190_arquivo'),
        ),
        migrations.AddIndex(
            model_name='spedcontribuicaoreg_c190',
            index=models.Index(fields=['c100'], name='sc_reg_c190_c100'),
        ),
        migrations.AddIndex(
            model_name='spedcontribuicaoreg_c190',
            index=models.Index(fields=['cod_item'], name='sc_reg_c190_coditem'),
        ),
        migrations.AddIndex(
            model_name='spedfiscalarquivo',
            index=models.Index(fields=['gdfcliente', 'competencia'], name='sf_arquivo_cli_comp'),
        ),
        migrations.AddIndex(
            model_name='spedfiscalarquivo',
            index=models.Index(fields=['empresa', 'competencia'], name='sf_arquivo_emp_comp'),
        ),
        migrations.AddIndex(
            model_name='spedfiscalarquivo',
            index=models.Index(fields=['data_carga'], name='sf_arquivo_data_carga'),
        ),
        migrations.AddIndex(
            model_name='spedfiscalarquivo',
            index=models.Index(fields=['hash_conteudo'], name='sf_arquivo_hash'),
        ),
        migrations.AddIndex(
            model_name='spedfiscalreg_0000',
            index=models.Index(fields=['arquivo'], name='sf_reg_0000_arquivo'),
        ),
        migrations.AddIndex(
            model_name='spedfiscalreg_0001',
            index=models.Index(fields=['arquivo'], name='sf_reg_0001_arquivo'),
        ),
        migrations.AddIndex(
            model_name='spedfiscalreg_0005',
            index=models.Index(fields=['arquivo'], name='sf_reg_0005_arquivo'),
        ),
        migrations.AddIndex(
            model_name='spedfiscalreg_0150',
            index=models.Index(fields=['arquivo'], name='sf_reg_0150_arquivo'),
        ),
        migrations.AddIndex(
            model_name='spedfiscalreg_0150',
            index=models.Index(fields=['cod_part'], name='sf_reg_0150_codpart'),
        ),
        migrations.AddIndex(
            model_name='spedfiscalreg_0190',
            index=models.Index(fields=['arquivo'], name='sf_reg_0190_arquivo'),
        ),
        migrations.AddIndex(
            model_name='spedfiscalreg_0200',
            index=models.Index(fields=['arquivo'], name='sf_reg_0200_arquivo'),
        ),
        migrations.AddIndex(
            model_name='spedfiscalreg_0200',
            index=models.Index(fields=['cod_item'], name='sf_reg_0200_coditem'),
        ),
        migrations.AddIndex(
            model_name='spedfiscalreg_c001',
            index=models.Index(fields=['arquivo'], name='sf_reg_c001_arquivo'),
        ),
        migrations.AddIndex(
            model_name='spedfiscalreg_c100',
            index=models.Index(fields=['arquivo'], name='sf_reg_c100_arquivo'),
        ),
        migrations.AddIndex(
            model_name='spedfiscalreg_c100',
            index=models.Index(fields=['chv_nfe'], name='sf_reg_c100_chv'),
        ),
        migrations.AddIndex(
            model_name='spedfiscalreg_c100',
            index=models.Index(fields=['dt_doc'], name='sf_reg_c100_dtdoc'),
        ),
        migrations.AddIndex(
            model_name='spedfiscalreg_c170',
            index=models.Index(fields=['arquivo'], name='sf_reg_c170_arquivo'),
        ),
        migrations.AddIndex(
            model_name='spedfiscalreg_c170',
            index=models.Index(fields=['c100'], name='sf_reg_c170_c100'),
        ),
        migrations.AddIndex(
            model_name='spedfiscalreg_d100',
            index=models.Index(fields=['arquivo'], name='sf_reg_d100_arquivo'),
        ),
        migrations.AddIndex(
            model_name='spedfiscalreg_d100',
            index=models.Index(fields=['chv_cte'], name='sf_reg_d100_chv'),
        ),
        migrations.AddIndex(
            model_name='spedfiscalreg_d100',
            index=models.Index(fields=['dt_doc'], name='sf_reg_d100_dtdoc'),
        ),
        migrations.AddIndex(
            model_name='spedfiscalregistro',
            index=models.Index(fields=['arquivo'], name='sf_registro_arquivo'),
        ),
        migrations.AddIndex(
            model_name='spedfiscalregistro',
            index=models.Index(fields=['arquivo', 'registro'], name='sf_registro_arq_reg'),
        ),
    ]
