# Generated by Django 6.0.1 on 2026-01-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cert',
            fields=[
                ('raiz_cnpj', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nm_arquivo_pfx', models.CharField(blank=True, max_length=100, null=True)),
                ('ini_validade', models.DateTimeField(blank=True, null=True)),
                ('fim_validade', models.DateTimeField(blank=True, null=True)),
                ('emissor', models.CharField(blank=True, max_length=100, null=True)),
                ('proprietario', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('arquivo_cert', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cert',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cod_cliente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('razao', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('cnpj', models.CharField(max_length=14)),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('cod_empresa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=14)),
                ('razao', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('fantasia', models.CharField(blank=True, max_length=60, null=True)),
                ('ie', models.CharField(blank=True, max_length=13, null=True)),
                ('im', models.CharField(blank=True, max_length=13, null=True)),
                ('tipo', models.CharField(blank=True, max_length=1, null=True)),
                ('matriz', models.BooleanField(blank=True, null=True)),
                ('crt', models.CharField(blank=True, max_length=1, null=True)),
                ('cnae', models.CharField(blank=True, max_length=7, null=True)),
                ('iest', models.CharField(blank=True, max_length=18, null=True)),
                ('suframa', models.CharField(blank=True, max_length=10, null=True)),
                ('chave_acesso', models.CharField(blank=True, max_length=40, null=True)),
                ('id_user', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'empresas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enderecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_empresa', models.IntegerField(blank=True, null=True)),
                ('seq', models.IntegerField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=70, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=20, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('bairro', models.CharField(blank=True, max_length=40, null=True)),
                ('cod_municipio', models.IntegerField(blank=True, null=True)),
                ('uf', models.IntegerField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('ie', models.CharField(blank=True, max_length=18, null=True)),
                ('im', models.CharField(blank=True, max_length=18, null=True)),
            ],
            options={
                'db_table': 'enderecos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrpEmpresas',
            fields=[
                ('grp_empresa', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'grp_empresas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoCliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'grupo_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('cod_municipio', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('municipio', models.CharField(blank=True, max_length=35, null=True)),
            ],
            options={
                'db_table': 'municipios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SiteImagem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imagem', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Site_imagem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solucoes',
            fields=[
                ('cod_solucoes', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'solucoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolucoesAcesso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'solucoes_acesso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subsolucoes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cod_subsolucoes', models.CharField(db_column='cod_subSolucoes', max_length=10)),
                ('descricao', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'subsolucoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubsolucoesAcesso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'subsolucoes_acesso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('uf', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('cod_ibge', models.CharField(blank=True, max_length=2, null=True)),
                ('nome', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'uf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserEmpresas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_empresas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('pk', models.CompositePrimaryKey('cod_empresa', 'usuario', blank=True, editable=False, primary_key=True, serialize=False)),
                ('cod_empresa', models.IntegerField()),
                ('usuario', models.IntegerField()),
                ('senha', models.CharField(blank=True, max_length=20, null=True)),
                ('nome', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
                ('admin', models.BooleanField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'db_table_comment': 'Tabela de Usußrios do sistema GDF',
                'managed': False,
            },
        ),
    ]
