# Generated by Django 6.0.1 on 2026-01-21 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solucoes',
            fields=[
                ('cod_solucao', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'solucoes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cert',
            fields=[
                ('raiz_cnpj', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nm_arquivo_pfx', models.CharField(blank=True, max_length=100, null=True)),
                ('ini_validade', models.DateTimeField(blank=True, null=True)),
                ('fim_validade', models.DateTimeField(blank=True, null=True)),
                ('emissor', models.CharField(blank=True, max_length=100, null=True)),
                ('proprietario', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('arquivo_cert', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cert',
                'managed': True,
                'indexes': [models.Index(fields=['cpf_cnpj'], name='cert_cpf_cnp_19ec5b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cod_cliente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('razao', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'clientes',
                'managed': True,
                'indexes': [models.Index(fields=['cnpj', 'razao'], name='clientes_cnpj_7b9982_idx')],
            },
        ),
        migrations.CreateModel(
            name='GrpEmpresas',
            fields=[
                ('grp_empresa', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=80, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.clientes')),
            ],
            options={
                'db_table': 'grp_empresas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('cod_empresa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('razao', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('fantasia', models.CharField(blank=True, max_length=60, null=True)),
                ('ie', models.CharField(blank=True, max_length=13, null=True)),
                ('im', models.CharField(blank=True, max_length=13, null=True)),
                ('tipo', models.CharField(blank=True, max_length=1, null=True)),
                ('matriz', models.BooleanField(blank=True, null=True)),
                ('crt', models.CharField(blank=True, max_length=1, null=True)),
                ('cnae', models.CharField(blank=True, max_length=7, null=True)),
                ('iest', models.CharField(blank=True, max_length=18, null=True)),
                ('suframa', models.CharField(blank=True, max_length=10, null=True)),
                ('chave_acesso', models.CharField(blank=True, max_length=40, null=True)),
                ('id_user', models.IntegerField(blank=True, null=True)),
                ('cert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.cert')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.clientes')),
                ('grp_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.grpempresas')),
            ],
            options={
                'db_table': 'empresas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GrupoCliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.clientes')),
                ('group', models.ForeignKey(db_column='Group_id', on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'db_table': 'grupo_cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SolucoesAcesso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.clientes')),
                ('solucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.solucoes')),
            ],
            options={
                'db_table': 'solucoes_acesso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subsolucoes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cod_subsolucao', models.CharField(db_column='cod_subSolucoes', max_length=15)),
                ('descricao', models.CharField(blank=True, max_length=50, null=True)),
                ('solucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.solucoes')),
            ],
            options={
                'db_table': 'subsolucoes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SubsolucoesAcesso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(db_column='Group_id', on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('subsolucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subsolucoes')),
            ],
            options={
                'db_table': 'subsolucoes_acesso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserEmpresas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_empresas',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='empresas',
            index=models.Index(fields=['cnpj', 'razao', 'fantasia'], name='empresas_cnpj_89aa02_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grupocliente',
            unique_together={('group', 'cliente')},
        ),
        migrations.AlterUniqueTogether(
            name='solucoesacesso',
            unique_together={('cliente', 'solucao')},
        ),
        migrations.AlterUniqueTogether(
            name='subsolucoesacesso',
            unique_together={('group', 'subsolucao')},
        ),
        migrations.AlterUniqueTogether(
            name='userempresas',
            unique_together={('empresa', 'user')},
        ),
    ]
