# Generated by Django 6.0.1 on 2026-01-19 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cert',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='clientes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='empresas',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='grpempresas',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='grupocliente',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='solucoes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='solucoesacesso',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='subsolucoes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='subsolucoesacesso',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userempresas',
            options={'managed': False},
        ),
    ]
