# Generated by Django 6.0.1 on 2026-01-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
