# Generated by Django 6.0.1 on 2026-01-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_clientes_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresas',
            name='id_user',
        ),
    ]
