# Generated by Django 6.0.1 on 2026-01-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_solucoes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solucoes',
            options={'managed': False},
        ),
    ]
