# Generated by Django 6.0.1 on 2026-01-16 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_solucoes_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enderecos',
        ),
        migrations.DeleteModel(
            name='Municipios',
        ),
        migrations.DeleteModel(
            name='SiteImagem',
        ),
        migrations.DeleteModel(
            name='Uf',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AlterModelOptions(
            name='cert',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='clientes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='empresas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='grpempresas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='grupocliente',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='solucoes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='solucoesacesso',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='subsolucoes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='subsolucoesacesso',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userempresas',
            options={'managed': True},
        ),
    ]
