# Generated by Django 6.0.1 on 2026-01-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_add_origem_dados_nfe'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='nfe',
            new_name='nfe_empresa_c3f6b4_idx',
            old_name='nfe_empresa_idx',
        ),
        migrations.AddField(
            model_name='nfe',
            name='usuario_atualizacao',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='nfe_emitente',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nfe_endereco',
            name='nome_municipio',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='nfe_endereco',
            name='nome_pais',
            field=models.CharField(blank=True, default='Brasil', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='nfe_identificacao',
            name='codigo_municipio',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='nfe_identificacao',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nfe_identificacao',
            name='finalidade_emissao',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='nfe_identificacao',
            name='forma_emissao',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='nfe_identificacao',
            name='modelo',
            field=models.CharField(blank=True, default='55', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='nfe_identificacao',
            name='natureza_operacao',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='nfe_identificacao',
            name='presenca_comprador',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='nfe_identificacao',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='nfe_identificacao',
            name='consumidor_final',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
