# Generated by Django 6.0.1 on 2026-01-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_nfe_empresa_idx_nfe_empresa_c3f6b4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfe_produto',
            name='cest',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='nfe_produto',
            name='cfop',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
