# Generated by Django 6.0.1 on 2026-01-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_nfe_produto_cest_nfe_produto_cfop'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfe_destinatario',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nfe_destinatario',
            name='isuf',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
