# Generated by Django 6.0.1 on 2026-02-11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_nfe_destinatario_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFe_Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('COMPRA', 'Compra'), ('MIRO', 'MIRO'), ('MIGO', 'MIGO'), ('OUTROS', 'Outros')], default='COMPRA', max_length=20)),
                ('numero_documento', models.CharField(max_length=40)),
                ('data_documento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='PENDENTE', max_length=20)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nfe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app.nfe')),
            ],
            options={
                'db_table': '"nfe"."nfe_documento"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NFe_DocumentoItem',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('sequencia', models.IntegerField()),
                ('material', models.CharField(blank=True, max_length=60, null=True)),
                ('descricao', models.CharField(blank=True, max_length=120, null=True)),
                ('quantidade', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('unidade', models.CharField(blank=True, max_length=10, null=True)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app.nfe_documento')),
                ('nfe_produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documento_itens', to='app.nfe_produto')),
            ],
            options={
                'db_table': '"nfe"."nfe_documento_item"',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='nfe_documento',
            index=models.Index(fields=['nfe', 'tipo_documento'], name='nfe_doc_nfe_3fb2bf_idx'),
        ),
        migrations.AddIndex(
            model_name='nfe_documento',
            index=models.Index(fields=['numero_documento'], name='nfe_doc_num_74c8be_idx'),
        ),
        migrations.AddIndex(
            model_name='nfe_documentoitem',
            index=models.Index(fields=['documento', 'sequencia'], name='nfe_docit_doc_32c9b7_idx'),
        ),
        migrations.AddIndex(
            model_name='nfe_documentoitem',
            index=models.Index(fields=['nfe_produto'], name='nfe_docit_nfe_2e43d6_idx'),
        ),
    ]
