# Generated by Django 6.0.1 on 2026-02-11 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_manifesto_documentos'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='nfe_documento',
            new_name='nfe_documen_nfe_id_143e75_idx',
            old_name='nfe_doc_nfe_3fb2bf_idx',
        ),
        migrations.RenameIndex(
            model_name='nfe_documento',
            new_name='nfe_documen_numero__4c343f_idx',
            old_name='nfe_doc_num_74c8be_idx',
        ),
        migrations.RenameIndex(
            model_name='nfe_documentoitem',
            new_name='nfe_documen_documen_1bb136_idx',
            old_name='nfe_docit_doc_32c9b7_idx',
        ),
        migrations.RenameIndex(
            model_name='nfe_documentoitem',
            new_name='nfe_documen_nfe_pro_094941_idx',
            old_name='nfe_docit_nfe_2e43d6_idx',
        ),
    ]
