# Generated by Django 6.0.1 on 2026-02-26 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_cargaxml_param_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargaxmlparam',
            name='modelos',
        ),
        migrations.AddField(
            model_name='cargaxmlparam',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.empresas'),
        ),
        migrations.RenameIndex(
            model_name='cargaxmljob',
            new_name='cargaxml_jo_cliente_763bcd_idx',
            old_name='cargaxml_jo_cliente_5f0b4a_idx',
        ),
        migrations.RenameIndex(
            model_name='cargaxmlparam',
            new_name='cargaxml_pa_cliente_ffd1f4_idx',
            old_name='cargaxml_pa_cliente_33e08f_idx',
        ),
    ]
