# Generated by Django 6.0.1 on 2026-02-27 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_create_db_schemas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTe_Endereco',
            fields=[
                ('id_endereco', models.AutoField(primary_key=True, serialize=False)),
                ('logradouro', models.CharField(blank=True, max_length=60, null=True)),
                ('numero', models.CharField(blank=True, max_length=60, null=True)),
                ('complemento', models.CharField(blank=True, max_length=60, null=True)),
                ('bairro', models.CharField(blank=True, max_length=60, null=True)),
                ('codigo_municipio', models.CharField(blank=True, max_length=7, null=True)),
                ('nome_municipio', models.CharField(blank=True, max_length=60, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('pais', models.CharField(blank=True, default='1058', max_length=4, null=True)),
                ('nome_pais', models.CharField(blank=True, default='Brasil', max_length=60, null=True)),
                ('telefone', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.EmailField(blank=True, max_length=60, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"cte"."cte_endereco"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NFSe_Endereco',
            fields=[
                ('id_endereco', models.AutoField(primary_key=True, serialize=False)),
                ('logradouro', models.CharField(blank=True, max_length=60, null=True)),
                ('numero', models.CharField(blank=True, max_length=60, null=True)),
                ('complemento', models.CharField(blank=True, max_length=60, null=True)),
                ('bairro', models.CharField(blank=True, max_length=60, null=True)),
                ('codigo_municipio', models.CharField(blank=True, max_length=7, null=True)),
                ('nome_municipio', models.CharField(blank=True, max_length=60, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('pais', models.CharField(blank=True, default='1058', max_length=4, null=True)),
                ('nome_pais', models.CharField(blank=True, default='Brasil', max_length=60, null=True)),
                ('telefone', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.EmailField(blank=True, max_length=60, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"nfse"."nfse_endereco"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CTe_Emitente',
            fields=[
                ('id_emitente', models.AutoField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('razao_social', models.CharField(max_length=120)),
                ('nome_fantasia', models.CharField(blank=True, max_length=60, null=True)),
                ('ie', models.CharField(blank=True, max_length=14, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('endereco', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cte_endereco')),
            ],
            options={
                'db_table': '"cte"."cte_emitente"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CTe_Destinatario',
            fields=[
                ('id_destinatario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('1', 'CNPJ'), ('2', 'CPF')], default='1', max_length=1)),
                ('documento', models.CharField(max_length=14)),
                ('razao_social', models.CharField(blank=True, max_length=120, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('endereco', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cte_endereco')),
            ],
            options={
                'db_table': '"cte"."cte_destinatario"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CTe_Identificacao',
            fields=[
                ('id_identificacao', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=9)),
                ('serie', models.CharField(max_length=3)),
                ('emissao', models.DateTimeField()),
                ('chave_acesso', models.CharField(max_length=44, unique=True)),
                ('modelo', models.CharField(default='57', max_length=2)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"cte"."cte_identificacao"',
                'managed': True,
                'indexes': [models.Index(fields=['chave_acesso', 'numero', 'serie'], name='cte_identif_chave_a_d950dc_idx'), models.Index(fields=['emissao'], name='cte_identif_emissao_a061ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='CTe',
            fields=[
                ('id_cte', models.AutoField(primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.empresas')),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cte_destinatario')),
                ('emitente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cte_emitente')),
                ('identificacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cte', to='app.cte_identificacao')),
            ],
            options={
                'db_table': '"cte"."cte"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CTe_Transporte',
            fields=[
                ('id_transporte', models.AutoField(primary_key=True, serialize=False)),
                ('modal', models.CharField(blank=True, max_length=1, null=True)),
                ('placa', models.CharField(blank=True, max_length=8, null=True)),
                ('uf_placa', models.CharField(blank=True, max_length=2, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cte_identificacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transporte', to='app.cte_identificacao')),
            ],
            options={
                'db_table': '"cte"."cte_transporte"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CTe_Valor',
            fields=[
                ('id_valor', models.AutoField(primary_key=True, serialize=False)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cte_identificacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valor', to='app.cte_identificacao')),
            ],
            options={
                'db_table': '"cte"."cte_valor"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NFSe_Identificacao',
            fields=[
                ('id_identificacao', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20)),
                ('emissao', models.DateTimeField()),
                ('competencia', models.DateTimeField(blank=True, null=True)),
                ('codigo_prefeitura', models.CharField(blank=True, max_length=7, null=True)),
                ('chave', models.CharField(max_length=44, unique=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"nfse"."nfse_identificacao"',
                'managed': True,
                'indexes': [models.Index(fields=['chave', 'numero'], name='nfse_identi_chave_c0b018_idx'), models.Index(fields=['emissao'], name='nfse_identi_emissao_a40de6_idx')],
            },
        ),
        migrations.CreateModel(
            name='NFSe_Prestador',
            fields=[
                ('id_prestador', models.AutoField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('razao_social', models.CharField(max_length=120)),
                ('nome_fantasia', models.CharField(blank=True, max_length=60, null=True)),
                ('ie', models.CharField(blank=True, max_length=14, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('endereco', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.nfse_endereco')),
            ],
            options={
                'db_table': '"nfse"."nfse_prestador"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NFSe_Servico',
            fields=[
                ('id_servico', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=240)),
                ('quantidade', models.DecimalField(decimal_places=4, default=1, max_digits=15)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('nfse_identificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='app.nfse_identificacao')),
            ],
            options={
                'db_table': '"nfse"."nfse_servico"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NFSe_Tomador',
            fields=[
                ('id_tomador', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('1', 'CNPJ'), ('2', 'CPF')], default='1', max_length=1)),
                ('documento', models.CharField(max_length=14)),
                ('razao_social', models.CharField(blank=True, max_length=120, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('endereco', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.nfse_endereco')),
            ],
            options={
                'db_table': '"nfse"."nfse_tomador"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NFSe',
            fields=[
                ('id_nfse', models.AutoField(primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.empresas')),
                ('identificacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nfse', to='app.nfse_identificacao')),
                ('prestador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.nfse_prestador')),
                ('tomador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.nfse_tomador')),
            ],
            options={
                'db_table': '"nfse"."nfse"',
                'managed': True,
            },
        ),
    ]
