# Generated by Django 5.2.11 on 2026-03-03 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_nfe_empresa_cascade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='grp_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.grpempresas'),
        ),
        migrations.CreateModel(
            name='CargaSpedParam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ativo', models.BooleanField(default=True)),
                ('horario', models.TimeField()),
                ('tipo_sped', models.CharField(choices=[('EFD_ICMS', 'EFD ICMS/IPI'), ('EFD_CONTRIB', 'EFD Contribuições'), ('ECD', 'ECD'), ('OUTROS', 'Outros')], default='EFD_ICMS', max_length=20)),
                ('diretorio', models.CharField(max_length=500)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ultima_execucao', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clientes')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.empresas')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargasped_params', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cargasped_param',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CargaSpedJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('RUNNING', 'Executando'), ('SUCCESS', 'Sucesso'), ('ERROR', 'Erro')], default='PENDING', max_length=10)),
                ('total_arquivos', models.IntegerField(default=0)),
                ('total_sucesso', models.IntegerField(default=0)),
                ('total_erro', models.IntegerField(default=0)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clientes')),
                ('usuario_execucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargasped_jobs', to=settings.AUTH_USER_MODEL)),
                ('parametro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cargaspedparam')),
            ],
            options={
                'db_table': 'cargasped_job',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='cargaspedparam',
            index=models.Index(fields=['cliente', 'ativo'], name='cargasped_p_cliente_d4d6ec_idx'),
        ),
        migrations.AddIndex(
            model_name='cargaspedjob',
            index=models.Index(fields=['cliente', 'status'], name='cargasped_j_cliente_88ec61_idx'),
        ),
    ]
