# Generated by Django 5.2.11 on 2026-03-03 15:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_create_schema_sped'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sped_Arquivo',
            fields=[
                ('id_arquivo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('C', 'Contribuição'), ('F', 'Fiscal')], help_text='C = Contribuição (EFD Contribuições), F = Fiscal (EFD ICMS/IPI)', max_length=1)),
                ('competencia', models.DateField(blank=True, help_text='Competência do arquivo (ex.: primeiro dia do mês)', null=True)),
                ('nome_arquivo', models.CharField(blank=True, max_length=255, null=True)),
                ('data_carga', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sped_arquivos', to='app.empresas')),
            ],
            options={
                'db_table': '"sped"."sped_arquivo"',
                'ordering': ['-data_carga'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sped_Contribuicao',
            fields=[
                ('id_contribuicao', models.AutoField(primary_key=True, serialize=False)),
                ('bloco', models.CharField(blank=True, max_length=10, null=True)),
                ('registro', models.CharField(blank=True, max_length=20, null=True)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('linha', models.IntegerField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_contribuicao', to='app.sped_arquivo')),
            ],
            options={
                'db_table': '"sped"."sped_contribuicao"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sped_Fiscal',
            fields=[
                ('id_fiscal', models.AutoField(primary_key=True, serialize=False)),
                ('bloco', models.CharField(blank=True, max_length=10, null=True)),
                ('registro', models.CharField(blank=True, max_length=20, null=True)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('linha', models.IntegerField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_fiscal', to='app.sped_arquivo')),
            ],
            options={
                'db_table': '"sped"."sped_fiscal"',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='sped_arquivo',
            index=models.Index(fields=['tipo'], name='sped_arquiv_tipo_942b25_idx'),
        ),
        migrations.AddIndex(
            model_name='sped_arquivo',
            index=models.Index(fields=['empresa', 'competencia'], name='sped_arquiv_empresa_657f2a_idx'),
        ),
        migrations.AddIndex(
            model_name='sped_arquivo',
            index=models.Index(fields=['data_carga'], name='sped_arquiv_data_ca_238fd1_idx'),
        ),
        migrations.AddIndex(
            model_name='sped_contribuicao',
            index=models.Index(fields=['arquivo'], name='sped_contri_arquivo_214550_idx'),
        ),
        migrations.AddIndex(
            model_name='sped_contribuicao',
            index=models.Index(fields=['arquivo', 'bloco'], name='sped_contri_arquivo_c0e7be_idx'),
        ),
        migrations.AddIndex(
            model_name='sped_fiscal',
            index=models.Index(fields=['arquivo'], name='sped_fiscal_arquivo_4ebebb_idx'),
        ),
        migrations.AddIndex(
            model_name='sped_fiscal',
            index=models.Index(fields=['arquivo', 'bloco'], name='sped_fiscal_arquivo_24094f_idx'),
        ),
    ]
