# Generated by Django 5.2.11 on 2026-03-04 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_nfe_informacoes_adicionais_xped'),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS "reprocessamento";',
            reverse_sql='DROP SCHEMA IF EXISTS "reprocessamento" CASCADE;',
        ),
        migrations.CreateModel(
            name='ReprocessamentoJob',
            fields=[
                ('id_job', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('CONFRONTO', 'Confronto SPED x NFe'), ('REPROCESSAR_ITEM', 'Reprocessar item'), ('REPROCESSAR_LOTE', 'Reprocessar lote')], db_index=True, max_length=25)),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('EM_EXECUCAO', 'Em execução'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro'), ('CANCELADO', 'Cancelado')], db_index=True, default='AGUARDANDO', max_length=20)),
                ('id_lote', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('ids_divergencias', models.JSONField(blank=True, null=True)),
                ('total_processados', models.IntegerField(default=0)),
                ('total_erros', models.IntegerField(default=0)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('usuario', models.CharField(blank=True, max_length=120, null=True)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Job de reprocessamento',
                'verbose_name_plural': 'Jobs de reprocessamento',
                'db_table': '"reprocessamento"."reprocessamento_job"',
                'ordering': ['-data_criacao'],
                'managed': True,
                'indexes': [models.Index(fields=['tipo', 'status'], name='reprocessam_tipo_77a21c_idx'), models.Index(fields=['data_criacao'], name='reprocessam_data_cr_6a8a2e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReprocessamentoLote',
            fields=[
                ('id_lote', models.BigAutoField(primary_key=True, serialize=False)),
                ('cod_empresa', models.CharField(db_index=True, max_length=10)),
                ('competencia', models.DateField(db_index=True, help_text='Competência (ex.: primeiro dia do mês)')),
                ('id_arquivo_sped', models.IntegerField(blank=True, db_index=True, null=True)),
                ('total_nfe_esperado', models.IntegerField(blank=True, default=0, null=True)),
                ('total_nfe_encontrado', models.IntegerField(blank=True, default=0, null=True)),
                ('total_divergencias', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_CONFRONTO', 'Em confronto'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDENTE', max_length=20)),
                ('mensagem_erro', models.TextField(blank=True, null=True)),
                ('usuario_criacao', models.CharField(blank=True, max_length=120, null=True)),
                ('usuario_atualizacao', models.CharField(blank=True, max_length=120, null=True)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lote de reprocessamento',
                'verbose_name_plural': 'Lotes de reprocessamento',
                'db_table': '"reprocessamento"."reprocessamento_lote"',
                'ordering': ['-data_criacao'],
                'managed': True,
                'indexes': [models.Index(fields=['cod_empresa', 'competencia'], name='reprocessam_cod_emp_8b8aa1_idx'), models.Index(fields=['status', 'data_criacao'], name='reprocessam_status_a78c27_idx')],
            },
        ),
        migrations.CreateModel(
            name='Divergencia',
            fields=[
                ('id_divergencia', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('NFE_AUSENTE_SPED', 'NF-e ausente no SPED'), ('SPED_AUSENTE_NFE', 'Registro SPED sem NF-e'), ('VALOR_DIFERENTE', 'Valor divergente'), ('CFOP_DIFERENTE', 'CFOP divergente'), ('DATA_EMISSAO_DIFERENTE', 'Data de emissão divergente'), ('CANCELAMENTO', 'Cancelamento/denegação'), ('OUTRO', 'Outra inconsistência')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_REPROCESSAMENTO', 'Em reprocessamento'), ('RESOLVIDA', 'Resolvida'), ('IGNORADA', 'Ignorada')], db_index=True, default='ABERTA', max_length=25)),
                ('chave_nfe', models.CharField(blank=True, db_index=True, max_length=44, null=True)),
                ('numero_nfe', models.CharField(blank=True, max_length=20, null=True)),
                ('serie_nfe', models.CharField(blank=True, max_length=5, null=True)),
                ('registro_sped', models.CharField(blank=True, max_length=20, null=True)),
                ('linha_sped', models.IntegerField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor_esperado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('valor_encontrado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('detalhe_json', models.JSONField(blank=True, null=True)),
                ('id_nfe', models.IntegerField(blank=True, db_index=True, null=True)),
                ('data_reprocessamento', models.DateTimeField(blank=True, null=True)),
                ('usuario_reprocessamento', models.CharField(blank=True, max_length=120, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divergencias', to='app.reprocessamentolote')),
            ],
            options={
                'verbose_name': 'Divergência',
                'verbose_name_plural': 'Divergências',
                'db_table': '"reprocessamento"."divergencia"',
                'ordering': ['-data_criacao'],
                'managed': True,
                'indexes': [models.Index(fields=['lote', 'tipo'], name='divergencia_lote_id_ac33e1_idx'), models.Index(fields=['chave_nfe'], name='divergencia_chave_n_a3c59f_idx'), models.Index(fields=['status'], name='divergencia_status_7a9e1c_idx')],
            },
        ),
    ]
