# Generated by Django 5.2.11 on 2026-03-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_reprocessamento_acesso_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='reprocessamentolote',
            name='escopo_empresas',
            field=models.CharField(choices=[('UMA', 'Uma empresa'), ('VARIAS', 'Várias empresas'), ('TODAS', 'Todas as empresas')], default='UMA', max_length=10),
        ),
        migrations.AlterField(
            model_name='reprocessamentolote',
            name='competencia',
            field=models.DateField(db_index=True, help_text='Competência do confronto (mês): armazenada como 1º dia do mês (ex.: 2025-03-01 = mar/2025)'),
        ),
    ]
