# Generated by Django 5.2.11 on 2026-03-04 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_reprocessamento_escopo_empresas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicaoPagamentoLote',
            fields=[
                ('id_reg', models.BigAutoField(primary_key=True, serialize=False)),
                ('chave_nfe', models.CharField(db_index=True, max_length=44)),
                ('numero_nfe', models.CharField(blank=True, max_length=20, null=True)),
                ('serie_nfe', models.CharField(blank=True, max_length=5, null=True)),
                ('condicao_pagamento_nfe', models.CharField(blank=True, max_length=120, null=True)),
                ('condicao_pagamento_sap', models.CharField(blank=True, max_length=60, null=True)),
                ('condicao_pagamento_sap_retorno', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO_SAP', 'Enviado ao SAP'), ('PROCESSADO_SAP', 'Processado no SAP')], db_index=True, default='PENDENTE', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condicoes_pagamento', to='app.reprocessamentolote')),
            ],
            options={
                'verbose_name': 'Condição de pagamento (lote)',
                'verbose_name_plural': 'Condições de pagamento (lote)',
                'db_table': '"reprocessamento"."condicao_pagamento_lote"',
                'ordering': ['chave_nfe'],
                'managed': True,
                'indexes': [models.Index(fields=['lote', 'status'], name='condicao_pa_lote_id_682219_idx')],
                'unique_together': {('lote', 'chave_nfe')},
            },
        ),
    ]
