# Generated by Django 5.2.11 on 2026-03-04 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_condicao_sap_retorno'),
    ]

    operations = [
        migrations.CreateModel(
            name='SapConnection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ashost', models.CharField(max_length=100)),
                ('sysnr', models.CharField(max_length=10)),
                ('client', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=50)),
                ('lang', models.CharField(max_length=5)),
                ('active', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.clientes')),
            ],
            options={
                'db_table': 'sapconnection',
                'managed': True,
            },
        ),
    ]
