# Generated by Django 5.2.11 on 2026-03-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_sap_connection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicaoParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicao_pagamento_nfe', models.CharField(blank=True, max_length=120, null=True)),
                ('condicao_pagamento_sap', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'Condição de pagamento',
                'verbose_name_plural': 'Condições de pagamento',
                'db_table': '"reprocessamento"."condicao_param"',
                'ordering': ['condicao_pagamento_nfe'],
                'managed': True,
                'indexes': [models.Index(fields=['condicao_pagamento_nfe', 'condicao_pagamento_sap'], name='condicao_pa_condica_72cf1b_idx')],
                'unique_together': {('condicao_pagamento_nfe', 'condicao_pagamento_sap')},
            },
        ),
    ]
