# Generated by Django 5.2.11 on 2026-03-04 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_condicaoparam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sped_Reg_C100',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('linha', models.IntegerField(blank=True, null=True)),
                ('ind_oper', models.CharField(blank=True, max_length=1, null=True)),
                ('ind_emit', models.CharField(blank=True, max_length=1, null=True)),
                ('cod_part', models.CharField(blank=True, max_length=60, null=True)),
                ('cod_mod', models.CharField(blank=True, max_length=2, null=True)),
                ('cod_sit', models.CharField(blank=True, max_length=2, null=True)),
                ('ser', models.CharField(blank=True, max_length=3, null=True)),
                ('num_doc', models.CharField(blank=True, max_length=9, null=True)),
                ('chv_nfe', models.CharField(blank=True, max_length=44, null=True)),
                ('dt_doc', models.DateField(blank=True, null=True)),
                ('dt_e_s', models.DateField(blank=True, null=True)),
                ('vl_doc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ind_frt', models.CharField(blank=True, max_length=1, null=True)),
                ('vl_frt', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_seg', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_out_da', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_bc_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_bc_icms_st', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_icms_st', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_ipi', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_pis', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_cofins', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_pis_st', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_cofins_st', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_c100', to='app.sped_arquivo')),
            ],
            options={
                'db_table': '"sped"."sped_reg_c100"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sped_Reg_C170',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('linha', models.IntegerField(blank=True, null=True)),
                ('num_item', models.CharField(blank=True, max_length=3, null=True)),
                ('cod_item', models.CharField(blank=True, max_length=60, null=True)),
                ('descr_compl', models.CharField(blank=True, max_length=255, null=True)),
                ('qtd', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('unid', models.CharField(blank=True, max_length=6, null=True)),
                ('vl_item', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_desc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ind_mov', models.CharField(blank=True, max_length=1, null=True)),
                ('cst_icms', models.CharField(blank=True, max_length=3, null=True)),
                ('cfop', models.CharField(blank=True, max_length=4, null=True)),
                ('cod_nat', models.CharField(blank=True, max_length=10, null=True)),
                ('vl_bc_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('aliq_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vl_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vl_bc_icms_st', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('aliq_st', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vl_icms_st', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cst_pis', models.CharField(blank=True, max_length=2, null=True)),
                ('vl_bc_pis', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('aliq_pis', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('vl_pis', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cst_cofins', models.CharField(blank=True, max_length=2, null=True)),
                ('vl_bc_cofins', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('aliq_cofins', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('vl_cofins', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_c170', to='app.sped_arquivo')),
                ('c100', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_c170', to='app.sped_reg_c100')),
            ],
            options={
                'db_table': '"sped"."sped_reg_c170"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sped_Registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registro', models.CharField(db_index=True, max_length=20)),
                ('linha', models.IntegerField(blank=True, null=True)),
                ('campos', models.JSONField(blank=True, default=dict)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='app.sped_arquivo')),
            ],
            options={
                'db_table': '"sped"."sped_registro"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sped_Reg_0000',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('linha', models.IntegerField(blank=True, null=True)),
                ('cod_ver', models.CharField(blank=True, max_length=3, null=True)),
                ('cod_fin', models.CharField(blank=True, max_length=1, null=True)),
                ('dt_ini', models.DateField(blank=True, null=True)),
                ('dt_fin', models.DateField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('ie', models.CharField(blank=True, max_length=14, null=True)),
                ('cod_mun', models.CharField(blank=True, max_length=7, null=True)),
                ('im', models.CharField(blank=True, max_length=15, null=True)),
                ('suframa', models.CharField(blank=True, max_length=9, null=True)),
                ('ind_perfil', models.CharField(blank=True, max_length=1, null=True)),
                ('ind_ativ', models.CharField(blank=True, max_length=1, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_0000', to='app.sped_arquivo')),
            ],
            options={
                'db_table': '"sped"."sped_reg_0000"',
                'managed': True,
                'indexes': [models.Index(fields=['arquivo'], name='sped_reg_00_arquivo_8d767f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sped_Reg_0001',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('linha', models.IntegerField(blank=True, null=True)),
                ('ind_mov', models.CharField(blank=True, max_length=1, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_0001', to='app.sped_arquivo')),
            ],
            options={
                'db_table': '"sped"."sped_reg_0001"',
                'managed': True,
                'indexes': [models.Index(fields=['arquivo'], name='sped_reg_00_arquivo_efda49_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sped_reg_c100',
            index=models.Index(fields=['arquivo'], name='sped_reg_c1_arquivo_c44b31_idx'),
        ),
        migrations.AddIndex(
            model_name='sped_reg_c100',
            index=models.Index(fields=['chv_nfe'], name='sped_reg_c1_chv_nfe_c1ff76_idx'),
        ),
        migrations.AddIndex(
            model_name='sped_reg_c100',
            index=models.Index(fields=['dt_doc'], name='sped_reg_c1_dt_doc_7973f1_idx'),
        ),
        migrations.AddIndex(
            model_name='sped_reg_c170',
            index=models.Index(fields=['arquivo'], name='sped_reg_c1_arquivo_7c8311_idx'),
        ),
        migrations.AddIndex(
            model_name='sped_reg_c170',
            index=models.Index(fields=['c100'], name='sped_reg_c1_c100_id_b1ea62_idx'),
        ),
        migrations.AddIndex(
            model_name='sped_registro',
            index=models.Index(fields=['arquivo'], name='sped_regist_arquivo_1ba485_idx'),
        ),
        migrations.AddIndex(
            model_name='sped_registro',
            index=models.Index(fields=['arquivo', 'registro'], name='sped_regist_arquivo_edcd8a_idx'),
        ),
    ]
