# Generated by Django 5.2.11 on 2026-03-04 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_sped_tabelas_por_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sped_fiscal',
            name='arquivo',
        ),
        migrations.DeleteModel(
            name='Sped_Contribuicao',
        ),
        migrations.DeleteModel(
            name='Sped_Fiscal',
        ),
    ]
