# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_sped_reg_0005_0150_0190_0200_c001_d100_c190'),
    ]

    operations = [
        migrations.AddField(
            model_name='sped_arquivo',
            name='hash_conteudo',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='SHA256 do conteúdo para evitar carga duplicada',
                max_length=64,
                null=True,
            ),
        ),
    ]
