# Generated by Django 5.2.11 on 2026-03-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_sped_arquivo_hash_conteudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sped_reg_0200',
            name='aliq_icms',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sped_reg_c170',
            name='aliq_icms',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sped_reg_c170',
            name='aliq_st',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sped_reg_c190',
            name='aliq_icms',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddIndex(
            model_name='sped_arquivo',
            index=models.Index(fields=['hash_conteudo'], name='sped_arquiv_hash_co_2dba80_idx'),
        ),
    ]
