# Generated by Django 5.2.11 on 2026-03-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_sped_decimal_overflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sped_arquivo',
            name='tipo',
            field=models.CharField(choices=[('C', 'Contribuição'), ('F', 'Fiscal')], help_text='Detectado automaticamente pelo arquivo (0000/cod_ver). C=Contribuição, F=Fiscal (EFD ICMS/IPI).', max_length=1),
        ),
        migrations.AlterField(
            model_name='sped_reg_c170',
            name='aliq_cofins',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sped_reg_c170',
            name='aliq_pis',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
    ]
