# Generated by Django 5.2.11 on 2026-03-04 20:41

import django.db.models.deletion
from django.db import migrations, models


def _drop_old_unique_add_new(apps, schema_editor):
    """Remove constraint antigo e adiciona novo com cliente."""
    from django.db import connection
    with connection.cursor() as c:
        c.execute("""
            SELECT conname FROM pg_constraint
            WHERE conrelid = '"reprocessamento"."condicao_param"'::regclass
            AND contype = 'u'
        """)
        rows = c.fetchall()
        for (conname,) in rows:
            c.execute(f'ALTER TABLE "reprocessamento"."condicao_param" DROP CONSTRAINT IF EXISTS "{conname}"')
        c.execute('''
            ALTER TABLE "reprocessamento"."condicao_param"
            ADD CONSTRAINT condicao_param_cli_nfe_sap_uniq
            UNIQUE (cod_cliente, condicao_pagamento_nfe, condicao_pagamento_sap)
        ''')


def _reverse(apps, schema_editor):
    from django.db import connection
    with connection.cursor() as c:
        c.execute('ALTER TABLE "reprocessamento"."condicao_param" DROP CONSTRAINT IF EXISTS condicao_param_cli_nfe_sap_uniq')
        c.execute('''
            ALTER TABLE "reprocessamento"."condicao_param"
            ADD CONSTRAINT condicao_param_nfe_sap_uniq
            UNIQUE (condicao_pagamento_nfe, condicao_pagamento_sap)
        ''')


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_sped_aliq_pis_cofins_overflow'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='condicaoparam',
            name='condicao_pa_condica_72cf1b_idx',
        ),
        migrations.AddField(
            model_name='condicaoparam',
            name='cliente',
            field=models.ForeignKey(blank=True, db_column='cod_cliente', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condicoes_param_reprocessamento', to='app.clientes'),
        ),
        migrations.RunPython(_drop_old_unique_add_new, _reverse),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='condicaoparam',
                    unique_together={('cliente', 'condicao_pagamento_nfe', 'condicao_pagamento_sap')},
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='condicaoparam',
            index=models.Index(fields=['cliente', 'condicao_pagamento_nfe', 'condicao_pagamento_sap'], name='condicao_pa_cod_cli_d14e1e_idx'),
        ),
    ]
