# Generated by Django 5.2.11 on 2026-03-05 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_nfe_cte_nfse_cliente'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cte',
            name='cte_cliente_idx',
        ),
        migrations.RemoveIndex(
            model_name='nfse',
            name='nfse_cliente_idx',
        ),
        migrations.RenameIndex(
            model_name='nfe',
            new_name='nfe_cod_cli_263006_idx',
            old_name='nfe_cliente_idx',
        ),
        migrations.RenameIndex(
            model_name='sped_arquivo',
            new_name='sped_arquiv_cod_cli_961b5b_idx',
            old_name='sped_arquiv_cliente_comp_idx',
        ),
        migrations.AlterField(
            model_name='condicaopagamentolote',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO_SAP', 'Enviado ao SAP'), ('PROCESSADO_SAP', 'Processado no SAP'), ('PROCESSADO_SAP_U', 'Atualizado no SAP (U)'), ('PROCESSADO_SAP_I', 'Processado no SAP (I)')], db_index=True, default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='cte',
            name='cliente',
            field=models.ForeignKey(blank=True, db_column='cod_cliente', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cte_docs', to='app.clientes'),
        ),
        migrations.AlterField(
            model_name='nfe',
            name='cliente',
            field=models.ForeignKey(blank=True, db_column='cod_cliente', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nfe_docs', to='app.clientes'),
        ),
        migrations.AlterField(
            model_name='nfse',
            name='cliente',
            field=models.ForeignKey(blank=True, db_column='cod_cliente', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nfse_docs', to='app.clientes'),
        ),
        migrations.AlterField(
            model_name='sped_arquivo',
            name='cliente',
            field=models.ForeignKey(blank=True, db_column='cod_cliente', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sped_arquivos', to='app.clientes'),
        ),
    ]
