# Generated by Django 5.2.11 on 2026-03-05 18:03

from django.db import migrations, models


def converter_status_para_1char(apps, schema_editor):
    """Converte status antigos (PENDENTE, etc) para 1 char (P, E, S, U, I)."""
    CondicaoPagamentoLote = apps.get_model('app', 'CondicaoPagamentoLote')
    mapa = {
        'PENDENTE': 'P',
        'ENVIADO_SAP': 'E',
        'PROCESSADO_SAP': 'S',
        'PROCESSADO_SAP_U': 'U',
        'PROCESSADO_SAP_I': 'I',
    }
    for antigo, novo in mapa.items():
        CondicaoPagamentoLote.objects.filter(status=antigo).update(status=novo)


def reverter_status(apps, schema_editor):
    """Reverte para valores antigos (para rollback)."""
    CondicaoPagamentoLote = apps.get_model('app', 'CondicaoPagamentoLote')
    mapa = {'P': 'PENDENTE', 'E': 'ENVIADO_SAP', 'S': 'PROCESSADO_SAP', 'U': 'PROCESSADO_SAP_U', 'I': 'PROCESSADO_SAP_I'}
    for novo, antigo in mapa.items():
        CondicaoPagamentoLote.objects.filter(status=novo).update(status=antigo)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_condicao_pagamento_status_u_i'),
    ]

    operations = [
        migrations.RunPython(converter_status_para_1char, reverter_status),
        migrations.AlterField(
            model_name='condicaopagamentolote',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('E', 'Enviado ao SAP'), ('S', 'Processado no SAP'), ('U', 'Atualizado no SAP (U)'), ('I', 'Processado no SAP (I)')], db_index=True, default='P', max_length=1),
        ),
    ]
