# Generated by Django 5.2.11

from django.db import migrations, models


def _remover_duplicatas_sql(apps, schema_editor):
    """Remove duplicatas antes de alterar unique constraint."""
    from django.db import connection
    # A tabela condicao_param tem id (PK), cod_cliente, condicao_pagamento_nfe, condicao_pagamento_sap
    # Após AddField, terá tipo_pagamento (default '')
    # Duplicatas: mesmo (cod_cliente, condicao_pagamento_nfe, tipo_pagamento)
    # Manter: o que tem condicao_pagamento_sap preenchida, ou o de menor id
    with connection.cursor() as c:
        c.execute("""
            WITH ranked AS (
                SELECT id,
                    ROW_NUMBER() OVER (
                        PARTITION BY cod_cliente, COALESCE(condicao_pagamento_nfe,''), COALESCE(tipo_pagamento,'')
                        ORDER BY (CASE WHEN (condicao_pagamento_sap IS NOT NULL AND TRIM(condicao_pagamento_sap) != '') THEN 0 ELSE 1 END),
                                 id
                    ) AS rn
                FROM "reprocessamento"."condicao_param"
            )
            DELETE FROM "reprocessamento"."condicao_param"
            WHERE id IN (SELECT id FROM ranked WHERE rn > 1)
        """)


def _alterar_unique_condicao_param(apps, schema_editor):
    """Remove constraint antiga e adiciona nova com tipo_pagamento."""
    from django.db import connection
    with connection.cursor() as c:
        c.execute("""
            SELECT conname FROM pg_constraint
            WHERE conrelid = '"reprocessamento"."condicao_param"'::regclass
            AND contype = 'u'
        """)
        rows = c.fetchall()
        for (conname,) in rows:
            c.execute(f'ALTER TABLE "reprocessamento"."condicao_param" DROP CONSTRAINT IF EXISTS "{conname}"')
        c.execute('''
            ALTER TABLE "reprocessamento"."condicao_param"
            ADD CONSTRAINT condicao_param_cli_nfe_tipo_uniq
            UNIQUE (cod_cliente, condicao_pagamento_nfe, tipo_pagamento)
        ''')


def _reverter_unique_condicao_param(apps, schema_editor):
    """Reverte para constraint antiga."""
    from django.db import connection
    with connection.cursor() as c:
        c.execute('ALTER TABLE "reprocessamento"."condicao_param" DROP CONSTRAINT IF EXISTS condicao_param_cli_nfe_tipo_uniq')
        c.execute('''
            ALTER TABLE "reprocessamento"."condicao_param"
            ADD CONSTRAINT condicao_param_cli_nfe_sap_uniq
            UNIQUE (cod_cliente, condicao_pagamento_nfe, condicao_pagamento_sap)
        ''')


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_condicao_pagamento_status_1char'),
    ]

    operations = [
        migrations.AddField(
            model_name='condicaoparam',
            name='tipo_pagamento',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='condicaopagamentolote',
            name='tipo_pagamento',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.RunPython(_remover_duplicatas_sql, migrations.RunPython.noop),
        migrations.RunPython(_alterar_unique_condicao_param, _reverter_unique_condicao_param),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='condicaoparam',
                    unique_together={('cliente', 'condicao_pagamento_nfe', 'tipo_pagamento')},
                ),
            ],
        ),
        migrations.RemoveIndex(
            model_name='condicaoparam',
            name='condicao_pa_cod_cli_d14e1e_idx',
        ),
        migrations.AddIndex(
            model_name='condicaoparam',
            index=models.Index(fields=['cliente', 'condicao_pagamento_nfe', 'tipo_pagamento'], name='condicao_pa_cli_nfe_tipo_idx'),
        ),
    ]
