# Generated by Django 5.2.11 on 2026-03-05 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_condicaoparam_tipo_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTe_Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(max_length=6)),
                ('descricao_evento', models.CharField(blank=True, max_length=100, null=True)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('data_evento', models.DateTimeField(blank=True, null=True)),
                ('numero_sequencia', models.IntegerField(default=1)),
                ('xml_evento', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"cte"."cte_evento"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NFe_Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(max_length=6)),
                ('descricao_evento', models.CharField(blank=True, max_length=100, null=True)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('data_evento', models.DateTimeField(blank=True, null=True)),
                ('numero_sequencia', models.IntegerField(default=1)),
                ('xml_evento', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"nfe"."nfe_evento"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NFSe_Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(blank=True, max_length=20, null=True)),
                ('descricao_evento', models.CharField(blank=True, max_length=100, null=True)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('data_evento', models.DateTimeField(blank=True, null=True)),
                ('numero_sequencia', models.IntegerField(default=1)),
                ('xml_evento', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"nfse"."nfse_evento"',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='condicaoparam',
            options={'managed': True, 'ordering': ['condicao_pagamento_nfe', 'tipo_pagamento'], 'verbose_name': 'Condição de pagamento', 'verbose_name_plural': 'Condições de pagamento'},
        ),
        migrations.RenameIndex(
            model_name='condicaoparam',
            new_name='condicao_pa_cod_cli_4ca465_idx',
            old_name='condicao_pa_cli_nfe_tipo_idx',
        ),
        migrations.AddField(
            model_name='cte_evento',
            name='cte_identificacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='app.cte_identificacao'),
        ),
        migrations.AddField(
            model_name='nfe_evento',
            name='nfe_identificacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='app.nfe_identificacao'),
        ),
        migrations.AddField(
            model_name='nfse_evento',
            name='nfse_identificacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='app.nfse_identificacao'),
        ),
        migrations.AddIndex(
            model_name='cte_evento',
            index=models.Index(fields=['cte_identificacao', 'tipo_evento'], name='cte_evento_cte_ide_df3d0e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cte_evento',
            unique_together={('cte_identificacao', 'tipo_evento', 'numero_sequencia')},
        ),
        migrations.AddIndex(
            model_name='nfe_evento',
            index=models.Index(fields=['nfe_identificacao', 'tipo_evento'], name='nfe_evento_nfe_ide_a6238a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nfe_evento',
            unique_together={('nfe_identificacao', 'tipo_evento', 'numero_sequencia')},
        ),
        migrations.AddIndex(
            model_name='nfse_evento',
            index=models.Index(fields=['nfse_identificacao', 'tipo_evento'], name='nfse_evento_nfse_id_51d4e6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nfse_evento',
            unique_together={('nfse_identificacao', 'tipo_evento', 'numero_sequencia')},
        ),
    ]
