"""
Django settings for GDF_PJT project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SAP RFC: configurar SDK antes de qualquer import do pyrfc
_NWRFC_PATH = BASE_DIR.parent / 'nwrfcsdk'
if _NWRFC_PATH.exists():
    os.environ.setdefault('SAPNWRFC_HOME', str(_NWRFC_PATH))
    _lib = _NWRFC_PATH / 'lib'
    if _lib.exists():
        ld_path = os.environ.get('LD_LIBRARY_PATH', '')
        if str(_lib) not in ld_path.split(':'):
            os.environ['LD_LIBRARY_PATH'] = f"{_lib}:{ld_path}".rstrip(':')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
import environ
from csp.constants import NONCE
from django.urls import reverse_lazy

env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Em produção (DEBUG=False) defina SECRET_KEY no .env; default só para desenvolvimento
_SECRET_DEFAULT = 'django-insecure-)+_kx-l8g8iu@t@k3y=mswm^+s#%)yu_d=kevi0vac+y#m0oc^'
SECRET_KEY = env('SECRET_KEY', default=_SECRET_DEFAULT)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)
if not DEBUG and SECRET_KEY == _SECRET_DEFAULT:
    import warnings
    warnings.warn('SECRET_KEY em produção deve ser definida no .env', UserWarning)
# Acesso pode ser realizado por todos. Padrão: ALLOWED_HOSTS = ['*'] (aceita qualquer Host).
# Para restringir, defina no .env: ALLOWED_HOSTS=homo.processit.com.br,localhost
_raw_hosts = env.list('ALLOWED_HOSTS', default=['*'])
ALLOWED_HOSTS = [h.strip() for h in _raw_hosts if (h and str(h).strip())] or ['*']

# HTTPS & Security Configuration
SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=False)  # True em produção
# Em DEBUG: cookies Secure=False para HTTP funcionar; em produção: True
SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=not DEBUG)
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=not DEBUG)
# Origens confiáveis para CSRF (HTTPS) - Django 4+ exige para POST via HTTPS. Não bloqueia acesso externo.
# Inclui URL pública e :443 para proxies/VPN. Se definir no .env, use lista separada por vírgula.
_default_csrf = [
    'https://homo.processit.com.br',
    'https://localhost:8500',
    'https://127.0.0.1:8500',
    'https://0.0.0.0:8500',
    'https://10.0.1.158:8500',
    'http://localhost:8500',
    'http://127.0.0.1:8500',
    'http://10.0.1.158:8500',
    'http://localhost:8600',
]
_raw_csrf = env.list('CSRF_TRUSTED_ORIGINS', default=[])
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _raw_csrf if (o and str(o).strip())] if _raw_csrf else _default_csrf

# Rate limiting (acesso externo/VPN: aumentar limites ou RATE_LIMIT_DISABLED=True se 429 em login)
RATE_LIMIT_DISABLED = env.bool('RATE_LIMIT_DISABLED', default=False)
RATE_LIMIT_LOGIN_MAX = env.int('RATE_LIMIT_LOGIN_MAX', default=15)   # requisições/min na tela de login
RATE_LIMIT_GENERAL_MAX = env.int('RATE_LIMIT_GENERAL_MAX', default=100)  # requisições/min por rota

# Subpath quando atrás do NGINX (ex.: https://homo.processit.com.br/gdf/). Deixe vazio para raiz.
FORCE_SCRIPT_NAME = env('FORCE_SCRIPT_NAME', default='/gdf')

# URL base do Streamlit para iframes (qualquer solução que use dashboard de análise).
# Uma única URL atende todos os dashboards (Vendas, Compras e futuros por solução).
# Ex. produção (com app em /gdf): STREAMLIT_BASE_URL=https://homo.processit.com.br/gdf/streamlit
# Ex. desenvolvimento: STREAMLIT_BASE_URL=http://127.0.0.1:8600
# Se vier lista separada por vírgula, usa só a primeira.
_raw = (env('STREAMLIT_BASE_URL', default='http://127.0.0.1:8600') or '').strip()
STREAMLIT_IFRAME_URL = _raw.split(',')[0].strip() if _raw else 'http://127.0.0.1:8600'

# Proxy reverso (NGINX): confiar nos headers para HTTPS e Host corretos
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True
SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=31536000)  # 1 ano
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=True)
SECURE_HSTS_PRELOAD = env.bool('SECURE_HSTS_PRELOAD', default=True)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_SECURITY_POLICY_REPORT_ONLY = False

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django_extensions",
    'app',
    'csp',  # Django CSP for Content-Security-Policy
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'app.security.middlewares.static_prefix_fix.StaticPrefixFixMiddleware',  # /static/ -> /gdf/static/ quando atrás de proxy
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Servir estáticos com Gunicorn (CSS/JS)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',  # Content-Security-Policy
    'app.security.middlewares.rate_limit.RateLimitMiddleware',  # Rate limiting
    'app.security.middlewares.session_fixation.SessionFixationMiddleware',  # Session security
    'app.security.middlewares.security_headers.SecurityHeadersMiddleware',  # XSS & Security headers
]

ROOT_URLCONF = 'GDF_PJT.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.solucoes_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'GDF_PJT.wsgi.application'

# Cache - Redis em produção (CACHE_URL ou REDIS_URL) ou LocMem em desenvolvimento
_cache_backend = env('CACHE_URL', default='') or env('REDIS_URL', default='')
if _cache_backend and _cache_backend.startswith('redis'):
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _cache_backend.split(',')[0].strip(),
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'gdf-cache',
        }
    }

# Session - Django default database sessions
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_CACHE_ALIAS = 'default'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': { # GDF
         'ENGINE': env('DB_ENGINE'),
         'NAME': env('DB_NAME'),          
         'USER': env('DB_USER'),         
         'PASSWORD': env('DB_PASSWORD'),   
         'HOST': env('DB_HOST'),        
         'PORT': env('DB_PORT'), 
        'OPTIONS': {
            'options': '-c search_path=public,nfe,cte,nfse,sped_fiscal,sped_contribuicao,reprocessamento'
        }         
    },                          
}
 
DATABASE_ROUTERS = [
    'GDF_PJT.routers.GDFRouter',
]

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Usar nomes de URL para respeitar FORCE_SCRIPT_NAME (/gdf/ em produção)
LOGIN_URL = reverse_lazy('Login')
LOGIN_REDIRECT_URL = reverse_lazy('Home')
LOGOUT_REDIRECT_URL = reverse_lazy('Login')

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = False
SESSION_COOKIE_AGE = env.int('SESSION_COOKIE_AGE', default=1800)
SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=not DEBUG)
SESSION_COOKIE_HTTPONLY = env.bool('SESSION_COOKIE_HTTPONLY', default=True)
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=not DEBUG)
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'

# Logging - Security & Audit
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'security': {
            'format': '[{asctime}] {levelname} - User: {username} | IP: {ip} | Action: {action} | Details: {details}',
            'style': '{',
        },
        'gdf_request': {
            'format': '[{asctime}] {levelname} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'gdf_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'gdf.log'),
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 5,
            'formatter': 'gdf_request',
            'encoding': 'utf-8',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'security.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'security',
        },
        'audit_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'audit.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'security': {
            'handlers': ['security_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'audit': {
            'handlers': ['audit_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'gdf': {
            'handlers': ['gdf_file'],
            'level': 'INFO' if not DEBUG else 'DEBUG',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Criar diretório de logs se não existir
import os
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# Com subpath (FORCE_SCRIPT_NAME=/gdf): STATIC_URL = /gdf/static/
STATIC_URL = (FORCE_SCRIPT_NAME.rstrip('/') + '/static/') if FORCE_SCRIPT_NAME else '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Celery
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://localhost:6379/1')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_BEAT_SCHEDULE = {
    'cargaxml-scan-params-every-minute': {
        'task': 'app.api.tasks.scan_cargaxml_params',
        'schedule': 60.0,
    },
}

CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": ("'self'",),

        "script-src": (
            "'self'",
            "'unsafe-inline'",
            "https://cdn.jsdelivr.net",
            "https://code.jquery.com",
            "https://cdnjs.cloudflare.com",
        ),

        "style-src": (
            "'self'",
            "'unsafe-inline'",
            "https://cdn.jsdelivr.net",
            "https://fonts.googleapis.com",
            "https://cdnjs.cloudflare.com",
        ),

        "img-src": ("'self'", "data:", "https:"),

        "font-src": (
            "'self'",
            "https://fonts.gstatic.com",
            "https://cdnjs.cloudflare.com",
        ),

        "connect-src": ("'self'", "https:"),

        # frame-src: 'self' + origens do .env (CSP_FRAME_SRC_EXTRA) para iframe do Dashboard (Streamlit).
        # Inclui http para desenvolvimento local (Streamlit em http://127.0.0.1:8600).
        # Ex. no .env: CSP_FRAME_SRC_EXTRA=https://homo.processit.com.br,https://localhost:8600
        "frame-src": ("'self'",) + tuple(env.list(
            "CSP_FRAME_SRC_EXTRA",
            default=[
                "http://localhost:8600",
                "http://127.0.0.1:8600",
                "https://localhost:8600",
                "https://127.0.0.1:8600",
                "https://homo.processit.com.br",
            ],
        )),

        "frame-ancestors": ("'none'",),
    }
}

